### ISSUE TITLE
long time no see

### ISSUE THREAD

**Issue by clarinetandmonkey** [dnglokpor/IdleFantasyHub#1]
Heyya Long time no see, it's me the person who caught most of the issues for the previous version of this. Just wanted to stop bye and say hi g'day

**Comment by dnglokpor** [comment]
> Heyya Long time no see, it's me the person who caught most of the issues for the previous version of this. Just wanted to stop bye and say hi g'day

Oh hey there. It indeed has been a while.
Thanks to the interest you showed to the last one, I was inspired to redo this in a better light. This one is pretty evolved compared to the other one. Auto exploration system and some graphics elements. Although I do have some issues in it that need fixing... when I get time.

If you have the time, give it a try as well and let me know what you think.

**Comment by clarinetandmonkey** [comment]
Alright, I'll be sure to make do of. The last bot was pretty good, aside from the few errors it had inside it. I'm looking forward to see how this one turned out and I'll let you know if I find any bugs, or anything you can add.
