### ISSUE TITLE
";guild" Command won't work

### ISSUE THREAD

**Issue by DovahBeat** [dnglokpor/IdleFantasyHub#3]
Hello, it's me again

First, to clarify my last ticket, yes I found the solution to it via a LOT of google searching, had to add something along the lines of an "intents" line of code towards the top of the bot, don't remember it off the top of my head.

Now, onto the real reason for this ticket.
It seems I cannot get the ";guild" command to work to establish player data. I assume I'm missing a file or something that I need to generate, like the "users.json" in the last bot. I just don't know where since this code is so different and I don't want to go around messing things up too much when I'm not entirely sure what they do.
I did notice, however, that the "records" folder generated, but there's nothing in any of the subfolders there.

Any help would be greatly appreciated, thank you!

**Comment by dnglokpor** [comment]
Would you care to share what the error stack trace is?

**Comment by DovahBeat** [comment]
can you tell me where to find that? I'm new to python and coding ^^' if it helps, the bot says "Something went wrong. Sorry, try something else." in response.

**Comment by DovahBeat** [comment]
in the event log it says this, hopefully this helps?

Tyrumi - World of Dragons	
21-Aug-24 11:45:45 28095 error on guild by AdventureBot#0569 on server Tyrumi - World of Dragons
21-Aug-24 11:45:45 28095 <class 'AttributeError'>
21-Aug-24 11:45:45 28095 'Member' object has no attribute 'avatar_url_as'

**Comment by dnglokpor** [comment]
Thanks for sharing this. I was able to reproduce this myself. It seems that maybe there was an API change in the Discord.py library which I am investigating right now.

The updater script was a serious work in progress. The goal was a to make a script that was able to automate updating the filesystem records of existing users in case I changed my filesystem scheme. This is a development only script and does not come into play when running the server.

**Comment by dnglokpor** [comment]
@DovahBeat The most recent PR merge should have fixed it. I have not tested everything but the basic commands work.
I never got around to it but I would suggest making some improvements like: 
1. The image gen system uses hardcoded values that don't scale from computer to computer
2. The filesystem record method should really be a database
have fun ;)

`;guild`
![image](https://github.com/user-attachments/assets/f54f32b1-f46c-4db6-90e5-961c700c7a1e)


`;hero`
![image](https://github.com/user-attachments/assets/aa010b05-6007-44e5-82c1-7ec66c649ac2)

`;profile`
![image](https://github.com/user-attachments/assets/9e1a93eb-1546-4250-9a4a-9045f65ac05d)
